apiVersion: v1
kind: Service
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: sdc-socialnetwork-db
    app-name: social-graph-mongodb
  namespace: sdc-socialnetwork-db
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: sdc-socialnetwork-db
    app-name: social-graph-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: sdc-socialnetwork-db
    app-name: social-graph-mongodb
  namespace: sdc-socialnetwork-db
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: sdc-socialnetwork-db
      app-name: social-graph-mongodb
  template:
    metadata:
      labels: 
        death-star-project: sdc-socialnetwork-db
        app-name: social-graph-mongodb
      name: social-graph-mongodb
    spec:
      containers:
      - name: social-graph-mongodb
        image: mongo
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
