---
apiVersion: v1
kind: Service
metadata:
  name: user-memcached
  labels:
    death-star-project: sdc-socialnetwork-db
    app-name: user-memcached
  namespace: sdc-socialnetwork-db
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: sdc-socialnetwork-db
    app-name: user-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-memcached
  labels:
    death-star-project: sdc-socialnetwork-db
    app-name: user-memcached
  namespace: sdc-socialnetwork-db
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: sdc-socialnetwork-db
      app-name: user-memcached
  template:
    metadata:
      labels: 
        death-star-project: sdc-socialnetwork-db
        app-name: user-memcached
      name: user-memcached
    spec:
      containers:
      - name: user-memcached
        image: memcached
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

