---
apiVersion: v1
kind: Service
metadata:
  name: upload-urls-sdc
  namespace: sdc-socialnetwork-func
spec:
  ports:
  - name: http 
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    faas_function: upload-urls-sdc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-urls-sdc
  labels:
    faas_function: upload-urls-sdc
  namespace: sdc-socialnetwork-func
spec:
  replicas: 1
  selector:
    matchLabels:
      faas_function: upload-urls-sdc
  template:
    metadata:
      labels: 
        faas_function: upload-urls-sdc
      name: upload-urls-sdc
    spec:
      containers:
      - name: upload-urls-sdc
        image: sdcbench/socialnetwork-func-upload-urls:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always

